@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-7xl px-5 py-10">
    <div><p class="text-sm text-cyan-600 dark:text-cyan-300">Collaboration</p><h1 class="mt-1 text-3xl font-semibold">Teams</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Use viewer, operator, and administrator roles to control shared infrastructure.</p></div>
    @if($errors->any())<div class="mt-5 rounded-xl border border-rose-200 dark:border-rose-400/20 bg-rose-50 dark:bg-rose-400/10 p-4 text-sm text-rose-700 dark:text-rose-200">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('teams.store') }}" class="panel mt-8 flex flex-wrap items-end gap-4">@csrf<label class="grow text-sm">New team name<input class="field" name="name" placeholder="Platform engineering"></label><button class="button-primary">Create team</button></form>
    <div class="mt-6 space-y-6">
        @forelse($owned as $team)
            <section class="panel">
                <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold">{{ $team->name }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Owner / {{ $team->memberships->count() }} members</p></div><form method="POST" action="{{ route('teams.switch',$team) }}">@csrf<button class="button-secondary">{{ auth()->user()->current_team_id === $team->id ? 'Active workspace' : 'Switch workspace' }}</button></form></div>
                <form method="POST" action="{{ route('teams.invite',$team) }}" class="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto]">@csrf<input class="field mt-0" type="email" name="email" placeholder="colleague@example.com"><select class="field mt-0" name="role"><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Administrator</option></select><button class="button-primary">Send invitation</button></form>
                <div class="mt-5 divide-y divide-slate-100 dark:divide-white/5">@foreach($team->memberships as $membership)<div class="flex flex-wrap items-center justify-between gap-4 py-3 text-sm"><span>{{ $membership->user->name }} / {{ $membership->user->email }}</span>@if($membership->role==='owner')<b class="capitalize">Owner</b>@else<div class="flex items-center gap-3"><form method="POST" action="{{ route('teams.members.role',[$team,$membership]) }}" class="flex items-center gap-2">@csrf @method('PATCH')<select class="rounded-lg border border-slate-200 dark:border-white/10 bg-white dark:bg-slate-900 px-2 py-1" name="role">@foreach(['viewer','operator','admin'] as $role)<option value="{{ $role }}" @selected($membership->role===$role)>{{ ucfirst($role) }}</option>@endforeach</select><button class="text-cyan-600 dark:text-cyan-300">Save</button></form><form method="POST" action="{{ route('teams.members.remove',[$team,$membership]) }}">@csrf @method('DELETE')<button class="text-rose-600 dark:text-rose-300">Remove</button></form></div>@endif</div>@endforeach @foreach($team->invitations->whereNull('accepted_at') as $invitation)<div class="flex justify-between py-3 text-sm text-amber-600 dark:text-amber-300"><span>{{ $invitation->email }} / invited as {{ $invitation->role }}</span><span>Expires {{ $invitation->expires_at->diffForHumans() }}</span></div>@endforeach</div>
            </section>
        @empty<div class="panel text-center text-slate-500 dark:text-slate-400">You do not own a team yet.</div>@endforelse
    </div>
    @if($memberships->count())<section class="panel mt-6"><h2 class="font-semibold">Teams you joined</h2><div class="mt-4 divide-y divide-slate-100 dark:divide-white/5">@foreach($memberships as $membership)<div class="flex items-center justify-between py-3 text-sm"><span>{{ $membership->team->name }} / {{ $membership->role }} / owned by {{ $membership->team->owner->email }}</span><form method="POST" action="{{ route('teams.switch',$membership->team) }}">@csrf<button class="text-cyan-600 dark:text-cyan-300">{{ auth()->user()->current_team_id === $membership->team_id ? 'Active' : 'Switch' }}</button></form></div>@endforeach</div></section>@endif
</div>
@endsection
