<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Admin\AdminBillingRequestController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminFeatureFlagController;
use App\Http\Controllers\Admin\AdminPlanController;
use App\Http\Controllers\Admin\AdminPostController;
use App\Http\Controllers\Admin\AdminSettingController;
use App\Http\Controllers\Admin\AdminUserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CloudAccountController;
use App\Http\Controllers\CloudServerImportController;
use App\Http\Controllers\CronJobController;
use App\Http\Controllers\CustomServerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeploymentController;
use App\Http\Controllers\FileManagerController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\ManagedDatabaseController;
use App\Http\Controllers\MonitoringAgentController;
use App\Http\Controllers\MonitoringController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\PasswordResetController;
use App\Http\Controllers\PhpExtensionController;
use App\Http\Controllers\PhpMyAdminController;
use App\Http\Controllers\QueueWorkerController;
use App\Http\Controllers\RemoteManagementController;
use App\Http\Controllers\RetryServerProvisioningController;
use App\Http\Controllers\ServerManagementController;
use App\Http\Controllers\ServerOperationController;
use App\Http\Controllers\ServerTeamController;
use App\Http\Controllers\SiteConfigurationController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\SitePackageController;
use App\Http\Controllers\SshKeyController;
use App\Http\Controllers\SslCertificateController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TerminalController;
use App\Http\Controllers\TwoFactorChallengeController;
use App\Http\Controllers\WebhookController;
use App\Http\Controllers\WordPressController;
use App\Http\Middleware\EnsurePublicSiteEnabled;
use App\Livewire\ServerProvisionWizard;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/install', [InstallController::class, 'show'])->name('install');
Route::post('/install', [InstallController::class, 'store'])->middleware('throttle:10,1');
// Every public-facing page sits behind one switch, so turning the marketing site off in
// settings cannot leave one of them reachable by its own URL.
Route::middleware(EnsurePublicSiteEnabled::class)->group(function () {
    Route::get('/', [PageController::class, 'home'])->name('home');
    Route::get('/about', [PageController::class, 'about'])->name('about');
    Route::get('/features', [PageController::class, 'features'])->name('features');
    Route::get('/use-cases', [PageController::class, 'useCases'])->name('use-cases');
    Route::get('/contact', [PageController::class, 'contact'])->name('contact');
    Route::post('/contact', [PageController::class, 'submitContact'])->middleware('throttle:5,1')->name('contact.submit');
    Route::get('/blog', [BlogController::class, 'index'])->name('blog');
    Route::get('/blog/{slug}', [BlogController::class, 'show'])->name('blog.show');
});
Route::post('/webhooks/sites/{site}', WebhookController::class)->middleware('throttle:60,1')->name('webhooks.site');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:5,1');
    Route::get('/register', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:5,1');
    Route::get('/two-factor-challenge', [TwoFactorChallengeController::class, 'create'])->name('two-factor.login');
    Route::post('/two-factor-challenge', [TwoFactorChallengeController::class, 'store'])->middleware('throttle:5,1');
    Route::get('/forgot-password', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetController::class, 'send'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/reset-password/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [PasswordResetController::class, 'reset'])->name('password.update');
});
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::get('/email/verify', fn () => view('auth.verify-email'))->middleware('auth')->name('verification.notice');
Route::get('/email/verify/{id}/{hash}', fn (EmailVerificationRequest $request) => tap(redirect('/dashboard'), fn () => $request->fulfill()))->middleware(['auth', 'signed'])->name('verification.verify');
Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('status', 'Verification link sent.');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');
Route::get('/dashboard', DashboardController::class)->middleware(['auth', 'verified'])->name('dashboard');
Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/billing', [BillingController::class, 'index'])->name('billing.index');
    Route::post('/billing/requests', [BillingController::class, 'requestPlan'])->name('billing.request');
    Route::post('/billing/checkout', [BillingController::class, 'checkout'])->middleware('throttle:10,1')->name('billing.checkout');
    Route::post('/billing/portal', [BillingController::class, 'portal'])->middleware('throttle:10,1')->name('billing.portal');
    Route::get('/billing/success', [BillingController::class, 'success'])->name('billing.success');
    Route::get('/teams', [TeamController::class, 'index'])->name('teams.index');
    Route::post('/teams', [TeamController::class, 'store'])->name('teams.store');
    Route::post('/teams/{team}/switch', [TeamController::class, 'switch'])->name('teams.switch');
    Route::post('/teams/{team}/invitations', [TeamController::class, 'invite'])->name('teams.invite');
    Route::get('/team-invitations/{teamInvitation}/{token}', [TeamController::class, 'accept'])->name('team-invitations.accept');
    Route::delete('/teams/{team}/members/{member}', [TeamController::class, 'remove'])->name('teams.members.remove');
    Route::patch('/teams/{team}/members/{member}/role', [TeamController::class, 'role'])->name('teams.members.role');
    Route::get('/account', [AccountController::class, 'show'])->name('account');
    Route::patch('/account/profile', [AccountController::class, 'profile']);
    Route::put('/account/password', [AccountController::class, 'password']);
    Route::post('/account/two-factor', [AccountController::class, 'enableTwoFactor']);
    Route::post('/account/two-factor/confirm', [AccountController::class, 'confirmTwoFactor']);
    Route::delete('/account/two-factor', [AccountController::class, 'disableTwoFactor']);
    Route::post('/account/tokens', [AccountController::class, 'token']);
    Route::delete('/account/tokens/{token}', [AccountController::class, 'destroyToken']);
    Route::delete('/account/sessions/{session}', [AccountController::class, 'destroySession']);

    Route::get('/cloud-accounts', [CloudAccountController::class, 'index'])->name('cloud-accounts');
    Route::post('/cloud-accounts', [CloudAccountController::class, 'store'])->middleware('throttle:5,1');
    Route::get('/cloud-accounts/{cloudAccount}/servers', [CloudServerImportController::class, 'index'])->name('cloud-accounts.servers');
    Route::post('/cloud-accounts/{cloudAccount}/servers', [CloudServerImportController::class, 'store'])->middleware('throttle:10,1')->name('cloud-accounts.servers.store');
    Route::delete('/cloud-accounts/{cloudAccount}', [CloudAccountController::class, 'destroy']);

    Route::get('/ssh-keys', [SshKeyController::class, 'index'])->name('ssh-keys');
    Route::post('/ssh-keys/generate', [SshKeyController::class, 'generate']);
    Route::post('/ssh-keys', [SshKeyController::class, 'store']);
    Route::get('/ssh-keys/{sshKey}/download', [SshKeyController::class, 'download'])->name('ssh-keys.download');
    Route::delete('/ssh-keys/{sshKey}', [SshKeyController::class, 'destroy']);

    Route::get('/servers', [ServerManagementController::class, 'index'])->name('servers.index');
    Route::get('/servers/create', ServerProvisionWizard::class)->name('servers.create');
    Route::get('/servers/custom', [CustomServerController::class, 'create'])->name('servers.custom');
    Route::post('/servers/custom', [CustomServerController::class, 'store'])->middleware('throttle:10,1')->name('servers.custom.store');
    Route::get('/servers/{server}/manage', [ServerManagementController::class, 'show'])->name('servers.manage');
    Route::delete('/servers/{server}', [ServerManagementController::class, 'destroy'])->name('servers.destroy');
    Route::post('/servers/{server}/retry-provisioning', RetryServerProvisioningController::class)->name('servers.retry-provisioning');
    Route::patch('/servers/{server}/team', [ServerTeamController::class, 'update'])->name('servers.team.update');
    Route::post('/servers/{server}/backup-policies', [BackupController::class, 'store'])->name('backup-policies.store');
    Route::patch('/backup-policies/{backupPolicy}/toggle', [BackupController::class, 'toggle'])->name('backup-policies.toggle');
    Route::post('/backup-policies/{backupPolicy}/run', [BackupController::class, 'run'])->name('backup-policies.run');
    Route::delete('/backup-policies/{backupPolicy}', [BackupController::class, 'destroy'])->name('backup-policies.destroy');
    Route::post('/database-backups/{databaseBackup}/restore', [BackupController::class, 'restoreDatabase'])->name('database-backups.restore');
    Route::post('/servers/{server}/snapshots', [BackupController::class, 'snapshot'])->name('snapshots.store');
    Route::post('/server-snapshots/{serverSnapshot}/restore', [BackupController::class, 'restoreSnapshot'])->name('snapshots.restore');
    Route::delete('/server-snapshots/{serverSnapshot}', [BackupController::class, 'destroySnapshot'])->name('snapshots.destroy');
    Route::post('/servers/{server}/phpmyadmin', [PhpMyAdminController::class, 'store'])->name('phpmyadmin.store');
    Route::delete('/servers/{server}/phpmyadmin', [PhpMyAdminController::class, 'destroy'])->name('phpmyadmin.destroy');
    Route::post('/servers/{server}/monitoring/rotate', [MonitoringController::class, 'rotate'])->name('monitoring.rotate');
    Route::delete('/servers/{server}/monitoring', [MonitoringController::class, 'disable'])->name('monitoring.disable');
    Route::get('/servers/{server}/monitoring/agent', MonitoringAgentController::class)->name('monitoring.agent');
    Route::post('/servers/{server}/alert-rules', [MonitoringController::class, 'storeRule'])->name('alert-rules.store');
    Route::delete('/alert-rules/{alertRule}', [MonitoringController::class, 'destroyRule'])->name('alert-rules.destroy');
    Route::post('/notification-channels', [MonitoringController::class, 'storeChannel'])->name('notification-channels.store');
    Route::delete('/notification-channels/{notificationChannel}', [MonitoringController::class, 'destroyChannel'])->name('notification-channels.destroy');
    Route::post('/servers/{server}/databases', [ManagedDatabaseController::class, 'store'])->name('databases.store');
    Route::delete('/databases/{managedDatabase}', [ManagedDatabaseController::class, 'destroy'])->name('databases.destroy');
    Route::post('/databases/{managedDatabase}/export', [ManagedDatabaseController::class, 'export'])->name('databases.export');
    Route::post('/databases/{managedDatabase}/import', [ManagedDatabaseController::class, 'import'])->name('databases.import');
    Route::get('/database-backups/{databaseBackup}/download', [ManagedDatabaseController::class, 'download'])->name('database-backups.download');
    Route::post('/servers/{server}/cron-jobs', [CronJobController::class, 'store'])->name('cron-jobs.store');
    Route::patch('/cron-jobs/{cronJob}/toggle', [CronJobController::class, 'toggle'])->name('cron-jobs.toggle');
    Route::delete('/cron-jobs/{cronJob}', [CronJobController::class, 'destroy'])->name('cron-jobs.destroy');
    Route::post('/servers/{server}/operations', [ServerOperationController::class, 'store'])->name('server-operations.store');
    Route::post('/servers/{server}/php-extensions', [PhpExtensionController::class, 'store'])->name('php-extensions.store');
    Route::post('/sites/{site}/ssl', [SslCertificateController::class, 'store'])->name('ssl.store');
    Route::post('/sites/{site}/cron-jobs', [CronJobController::class, 'storeForSite'])->name('sites.cron-jobs.store');
    Route::post('/sites/{site}/workers', [QueueWorkerController::class, 'store'])->name('workers.store');
    Route::delete('/workers/{queueWorker}', [QueueWorkerController::class, 'destroy'])->name('workers.destroy');
    Route::post('/workers/{queueWorker}/status', [QueueWorkerController::class, 'status'])->name('workers.status');
    Route::post('/sites/{site}/packages', [SitePackageController::class, 'store'])->name('site-packages.store');
    Route::delete('/sites/{site}/packages', [SitePackageController::class, 'destroy'])->name('site-packages.destroy');
    Route::post('/sites/{site}/packages/check', [SitePackageController::class, 'check'])->name('site-packages.check');
    Route::post('/sites/{site}/horizon-admins', [SitePackageController::class, 'horizonAdmins'])->name('site-horizon-admins.update');
    Route::get('/sites', [SiteController::class, 'index'])->name('sites.index');
    Route::get('/sites/create', [SiteController::class, 'create'])->name('sites.create');
    Route::post('/sites', [SiteController::class, 'store'])->name('sites.store');
    Route::get('/sites/{site}', [SiteController::class, 'show'])->name('sites.show');
    Route::get('/sites/{site}/remote', RemoteManagementController::class)->name('sites.remote');
    Route::post('/sites/{site}/configurations', [SiteConfigurationController::class, 'store'])->name('site-configurations.store');
    Route::post('/site-configurations/{siteConfiguration}/rollback', [SiteConfigurationController::class, 'rollback'])->name('site-configurations.rollback');
    Route::post('/sites/{site}/files', [FileManagerController::class, 'store'])->name('site-files.store');
    Route::get('/file-operations/{fileOperation}/download', [FileManagerController::class, 'download'])->name('site-files.download');
    Route::post('/sites/{site}/terminal', [TerminalController::class, 'store'])->middleware('throttle:10,1')->name('terminal.store');
    Route::patch('/sites/{site}', [SiteController::class, 'update'])->name('sites.update');
    Route::put('/sites/{site}/environment', [SiteController::class, 'environment'])->name('sites.environment');
    Route::post('/sites/{site}/deployments', [SiteController::class, 'deploy'])->name('sites.deploy');
    Route::post('/sites/{site}/rollbacks/{deployment}', [SiteController::class, 'rollback'])->name('sites.rollback');
    Route::delete('/sites/{site}', [SiteController::class, 'destroy'])->name('sites.destroy');
    Route::post('/sites/{site}/queue-health', [SiteController::class, 'queueHealth'])->name('sites.queue-health');
    Route::post('/sites/{site}/wordpress-status', [SiteController::class, 'wordpressStatus'])->name('sites.wordpress-status');
    Route::post('/sites/{site}/wordpress/manage', [WordPressController::class, 'manage'])->name('wordpress.manage');
    Route::post('/sites/{site}/wordpress/install', [WordPressController::class, 'install'])->name('wordpress.install');
    Route::post('/sites/{site}/wordpress/refresh', [WordPressController::class, 'refresh'])->name('wordpress.refresh');
    Route::post('/sites/{site}/wordpress/backups', [WordPressController::class, 'backup'])->name('wordpress.backup');
    Route::post('/site-backups/{siteBackup}/restore', [WordPressController::class, 'restore'])->name('wordpress.restore');
    Route::get('/deployments/{deployment}', [DeploymentController::class, 'show'])->name('deployments.show');
    Route::post('/deployments/{deployment}/cancel', [DeploymentController::class, 'cancel'])->name('deployments.cancel');
    Route::post('/deployments/{deployment}/retry', [DeploymentController::class, 'retry'])->name('deployments.retry');

    Route::prefix('admin')->middleware('admin')->name('admin.')->group(function () {
        Route::get('/', [AdminDashboardController::class, 'overview'])->name('dashboard');
        Route::get('/users', [AdminDashboardController::class, 'users'])->name('users');
        Route::get('/plans', [AdminDashboardController::class, 'plans'])->name('plans');
        Route::get('/feature-flags', [AdminDashboardController::class, 'features'])->name('features');
        Route::get('/billing-review', [AdminDashboardController::class, 'billing'])->name('billing');
        Route::get('/payments', [AdminDashboardController::class, 'payments'])->name('payments');
        Route::get('/settings', [AdminDashboardController::class, 'settings'])->name('settings');
        Route::get('/audit', [AdminDashboardController::class, 'audit'])->name('audit');
        Route::get('/posts', [AdminPostController::class, 'index'])->name('posts');
        Route::post('/posts', [AdminPostController::class, 'store'])->name('posts.store');
        Route::patch('/posts/{post}', [AdminPostController::class, 'update'])->name('posts.update');
        Route::patch('/posts/{post}/publish', [AdminPostController::class, 'publish'])->name('posts.publish');
        Route::delete('/posts/{post}', [AdminPostController::class, 'destroy'])->name('posts.destroy');
        Route::patch('/users/{user}/suspension', [AdminUserController::class, 'suspend'])->name('users.suspend');
        Route::patch('/users/{user}/role', [AdminUserController::class, 'role'])->name('users.role');
        Route::post('/users/{user}/subscription', [AdminUserController::class, 'subscription'])->name('users.subscription');
        Route::post('/plans', [AdminPlanController::class, 'store'])->name('plans.store');
        Route::patch('/plans/{plan}', [AdminPlanController::class, 'update'])->name('plans.update');
        Route::patch('/plans/{plan}/stripe', [AdminPlanController::class, 'stripe'])->name('plans.stripe');
        Route::delete('/plans/{plan}', [AdminPlanController::class, 'destroy'])->name('plans.destroy');
        Route::post('/feature-flags', [AdminFeatureFlagController::class, 'store'])->name('flags.store');
        Route::patch('/feature-flags/{featureFlag}', [AdminFeatureFlagController::class, 'update'])->name('flags.update');
        Route::patch('/billing-requests/{billingRequest}', [AdminBillingRequestController::class, 'update'])->name('billing-requests.update');
        Route::put('/settings', [AdminSettingController::class, 'update'])->name('settings.update');
        Route::post('/settings/logo', [AdminSettingController::class, 'logo'])->name('settings.logo');
        Route::delete('/settings/logo', [AdminSettingController::class, 'destroyLogo'])->name('settings.logo.destroy');
        Route::put('/settings/mail', [AdminSettingController::class, 'mail'])->name('settings.mail');
        Route::post('/settings/mail/test', [AdminSettingController::class, 'testMail'])->middleware('throttle:6,1')->name('settings.mail.test');
    });
});
