@extends('layouts.app')
@section('content')
<div class="mx-auto max-w-7xl px-5 py-10">
    <div><p class="text-sm text-cyan-600 dark:text-cyan-300">Subscription</p><h1 class="mt-1 text-3xl font-semibold">Plans and usage</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Current plan: {{ $plan?->name ?? 'Unmetered legacy account' }} @if($subscription?->current_period_ends_at)/ renews or ends {{ $subscription->current_period_ends_at->toFormattedDateString() }}@endif</p></div>
    <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($usage as $resource=>$value)<div class="panel p-5"><div class="flex justify-between text-sm"><span class="capitalize text-slate-500 dark:text-slate-400">{{ str_replace('_',' ',$resource) }}</span><span>{{ $value['used'] }} / {{ $value['limit'] < 0 ? 'Unlimited' : $value['limit'] }}</span></div>@if($value['limit']>0)<div class="mt-3 h-2 rounded bg-slate-100 dark:bg-white/10"><div class="h-full rounded bg-cyan-400" style="width:{{ min(100,$value['used']*100/$value['limit']) }}%"></div></div>@endif</div>@endforeach</div>
    <div class="mt-8 grid gap-6 lg:grid-cols-3">@foreach($plans as $available)<article class="panel flex flex-col"><div class="flex items-start justify-between"><div><h2 class="text-xl font-semibold">{{ $available->name }}</h2><p class="mt-2 text-3xl">${{ number_format($available->monthly_price/100,2) }}<small class="text-sm text-slate-500 dark:text-slate-400">/month</small></p></div>@if($plan?->id===$available->id)<span class="rounded-full bg-emerald-50 dark:bg-emerald-400/10 px-3 py-1 text-xs text-emerald-600 dark:text-emerald-300">Current</span>@endif</div><div class="mt-5 grow space-y-2 text-sm text-slate-500 dark:text-slate-400">@foreach($available->limits as $key=>$limit)<p>{{ ucfirst(str_replace('_',' ',$key)) }}: {{ $limit<0?'Unlimited':$limit }}</p>@endforeach</div>@if($plan?->id!==$available->id)<form method="POST" action="{{ route('billing.request') }}" class="mt-6">@csrf<input type="hidden" name="plan_id" value="{{ $available->id }}"><select class="field" name="billing_cycle"><option value="monthly">Monthly billing</option><option value="yearly">Yearly billing</option></select><textarea class="field" name="customer_note" placeholder="Billing or purchase-order notes"></textarea><button class="button-primary mt-4 w-full">Request this plan</button></form>@endif</article>@endforeach</div>
    <section class="panel mt-8"><h2 class="font-semibold">Plan requests</h2><div class="mt-4 divide-y divide-slate-100 dark:divide-white/5">@forelse($requests as $change)<div class="flex justify-between py-3 text-sm"><span>{{ $change->plan->name }} / {{ $change->billing_cycle }}</span><span class="capitalize">{{ $change->status }}</span></div>@empty<p class="py-4 text-sm text-slate-500 dark:text-slate-400">No plan change requests.</p>@endforelse</div></section>
    @include('billing.partials.stripe')
</div>
@endsection
