<div class="mx-auto max-w-4xl px-5 py-10">
    <div class="mb-8 flex items-end justify-between"><div><p class="text-sm text-cyan-600 dark:text-cyan-300">New infrastructure</p><h1 class="mt-1 text-3xl font-semibold">Provision a server</h1></div><span class="text-sm text-slate-500 dark:text-slate-400">Step {{ $step }} of 5</span></div>
    <div class="mb-8 grid grid-cols-5 gap-2">@for($i=1;$i<=5;$i++)<div class="h-1.5 rounded-full {{ $i <= $step ? 'bg-cyan-400' : 'bg-slate-100 dark:bg-white/10' }}"></div>@endfor</div>
    <section class="rounded-3xl border border-slate-200 dark:border-white/10 bg-white dark:bg-white/[.04] p-6 sm:p-8" wire:loading.class="opacity-60">
        @if($step === 1)<h2 class="text-xl font-semibold">Choose a cloud account</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">CloudDeck will provision through a validated provider connection.</p><div class="mt-6 grid gap-3">@forelse($accounts as $account)<label class="flex cursor-pointer items-center gap-4 rounded-2xl border p-4 {{ $cloudAccountId === $account->id ? 'border-cyan-400 bg-cyan-50 dark:bg-cyan-400/10' : 'border-slate-200 dark:border-white/10' }}"><input type="radio" wire:model.live="cloudAccountId" value="{{ $account->id }}"><span><b>{{ $account->name }}</b><small class="block capitalize text-slate-500 dark:text-slate-400">{{ $account->provider }} · validated {{ $account->validated_at->diffForHumans() }}</small></span></label>@empty<p class="rounded-xl border border-amber-200 dark:border-amber-400/20 bg-amber-50 dark:bg-amber-400/10 p-4 text-amber-700 dark:text-amber-200">Connect a <a class="underline" href="/cloud-accounts">cloud account</a> first.</p>@endforelse</div>
        @elseif($step === 2)<h2 class="text-xl font-semibold">Server configuration</h2><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="text-sm">Region<select wire:model="region" class="field"><option value="">Select region</option>@foreach($regions as $item)<option value="{{ $item['slug'] }}">{{ $item['name'] }}</option>@endforeach</select></label><label class="text-sm">Size<select wire:model="size" class="field"><option value="">Select size</option>@foreach($sizes as $item)<option value="{{ $item['slug'] }}">{{ $item['vcpus'] }} vCPU · {{ round($item['memory']/1024,1) }} GB · ${{ $item['price_monthly'] }}/mo</option>@endforeach</select></label><label class="text-sm sm:col-span-2">Ubuntu image<select wire:model="image" class="field">@foreach($images as $item)<option value="{{ $item['slug'] }}">{{ $item['name'] }}</option>@endforeach</select></label></div>
        @elseif($step === 3)<h2 class="text-xl font-semibold">Select a managed SSH key</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">A managed key lets the provisioning workers securely bootstrap the server.</p><div class="mt-6 grid gap-3">@forelse($keys as $key)<label class="flex cursor-pointer items-center gap-4 rounded-2xl border p-4 {{ $sshKeyId === $key->id ? 'border-cyan-400 bg-cyan-50 dark:bg-cyan-400/10' : 'border-slate-200 dark:border-white/10' }}"><input type="radio" wire:model="sshKeyId" value="{{ $key->id }}"><span><b>{{ $key->name }}</b><small class="block font-mono text-slate-500 dark:text-slate-400">{{ $key->fingerprint }}</small></span></label>@empty<p class="rounded-xl border border-amber-200 dark:border-amber-400/20 bg-amber-50 dark:bg-amber-400/10 p-4 text-amber-700 dark:text-amber-200">Generate a managed key under <a class="underline" href="/ssh-keys">SSH keys</a>.</p>@endforelse</div>
        @elseif($step === 4)<h2 class="text-xl font-semibold">Identify your server</h2><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="text-sm">Display name<input wire:model="name" class="field" placeholder="Production API"></label><label class="text-sm">Hostname<input wire:model="hostname" class="field" placeholder="app-server-01"></label></div>
        @else<h2 class="text-xl font-semibold">Review and deploy</h2><dl class="mt-6 grid gap-4 rounded-2xl border border-slate-200 dark:border-white/10 p-5 sm:grid-cols-2">@foreach(['Name'=>$name,'Hostname'=>$hostname,'Region'=>$region,'Size'=>$size,'Image'=>$image] as $label=>$value)<div><dt class="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">{{ $label }}</dt><dd class="mt-1 font-medium">{{ $value }}</dd></div>@endforeach</dl><p class="mt-5 text-sm text-slate-500 dark:text-slate-400">Provisioning runs asynchronously. You can leave the dashboard while CloudDeck completes installation.</p>@endif
        @error('cloudAccountId')<p class="mt-4 text-sm text-rose-600 dark:text-rose-300">{{ $message }}</p>@enderror @foreach(['region','size','image','sshKeyId','name','hostname'] as $field)@error($field)<p class="mt-2 text-sm text-rose-600 dark:text-rose-300">{{ $message }}</p>@enderror @endforeach
        <div class="mt-8 flex justify-between">@if($step>1)<button wire:click="back" class="rounded-xl border border-slate-200 dark:border-white/10 px-5 py-3">Back</button>@else<span></span>@endif @if($step<5)<button wire:click="next" wire:loading.attr="disabled" class="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">Continue</button>@else<button wire:click="deploy" wire:loading.attr="disabled" class="rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-slate-950">Deploy server</button>@endif</div>
    </section>
</div>
