<div x-cloak x-show="tab==='backups'" class="mt-6 space-y-6">
    <div class="grid gap-6 lg:grid-cols-[400px_1fr]">
        <form method="POST" action="{{ route('backup-policies.store', $server) }}" class="panel h-fit">@csrf
            <h2 class="font-semibold">Automated backup policy</h2>
            <label class="mt-4 block text-sm">Name<input class="field" name="name" placeholder="Nightly production"></label>
            <label class="mt-4 block text-sm">Recovery point<select class="field" name="type" x-model="backupType"><option value="database">Database export</option><option value="snapshot">Provider snapshot</option></select></label>
            <label x-show="backupType==='database'" class="mt-4 block text-sm">Database<select class="field" name="managed_database_id"><option value="">Select database</option>@foreach($server->databases as $database)<option value="{{ $database->id }}">{{ $database->name }}</option>@endforeach</select></label>
            <label class="mt-4 block text-sm">Frequency<select class="field" name="frequency" x-model="frequency"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>
            <div class="grid grid-cols-2 gap-3"><label class="mt-4 block text-sm">Run at<input class="field" type="time" name="run_at" value="02:00"></label><label class="mt-4 block text-sm">Timezone<input class="field" name="timezone" value="{{ auth()->user()->timezone ?? 'UTC' }}"></label></div>
            <label x-show="frequency==='weekly'" class="mt-4 block text-sm">Weekday<select class="field" name="weekday"><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="0">Sunday</option></select></label>
            <label x-show="frequency==='monthly'" class="mt-4 block text-sm">Day of month<input class="field" type="number" name="day_of_month" min="1" max="28" value="1"></label>
            <label class="mt-4 block text-sm">Recovery points to keep<input class="field" type="number" name="retention_count" min="1" max="100" value="7"></label>
            <button class="button-primary mt-5">Create policy</button>
        </form>
        <div class="space-y-3">@forelse($server->backupPolicies as $policy)<article class="panel"><div class="flex flex-wrap justify-between gap-4"><div><h3 class="font-medium">{{ $policy->name }}</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ $policy->type === 'database' ? $policy->database?->name : 'Full provider snapshot' }} / {{ $policy->frequency }} at {{ $policy->run_at }} {{ $policy->timezone }} / keep {{ $policy->retention_count }}</p><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{ $policy->enabled ? 'Next '.$policy->next_run_at?->diffForHumans() : 'Disabled' }}</p></div><span class="text-sm {{ $policy->enabled ? 'text-emerald-600 dark:text-emerald-300' : 'text-slate-500 dark:text-slate-400' }}">{{ $policy->enabled ? 'Enabled' : 'Paused' }}</span></div><div class="mt-4 flex flex-wrap gap-3"><form method="POST" action="{{ route('backup-policies.run', $policy) }}">@csrf<button class="button-primary">Run now</button></form><form method="POST" action="{{ route('backup-policies.toggle', $policy) }}">@csrf @method('PATCH')<button class="button-secondary">{{ $policy->enabled ? 'Pause' : 'Enable' }}</button></form><form method="POST" action="{{ route('backup-policies.destroy', $policy) }}">@csrf @method('DELETE')<button class="button-secondary text-rose-600 dark:text-rose-300">Remove</button></form></div></article>@empty<div class="panel text-center text-slate-500 dark:text-slate-400">No automated backup policies.</div>@endforelse</div>
    </div>
    <section class="panel"><div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="font-semibold">Provider snapshots</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Restoring replaces the server disk. Type the hostname to authorize it.</p></div><form method="POST" action="{{ route('snapshots.store', $server) }}" class="flex gap-2">@csrf<input class="field mt-0" name="name" value="{{ $server->hostname }}-manual-{{ now()->format('Ymd') }}"><button class="button-primary">Create snapshot</button></form></div><div class="mt-5 divide-y divide-slate-100 dark:divide-white/5">@forelse($server->snapshots as $snapshot)<div class="py-4"><div class="flex flex-wrap justify-between gap-3"><span>{{ $snapshot->name }} <small class="ml-2 text-slate-500 dark:text-slate-400">{{ $snapshot->status }} @if($snapshot->size_gigabytes)/ {{ $snapshot->size_gigabytes }} GB @endif</small></span><form method="POST" action="{{ route('snapshots.destroy', $snapshot) }}">@csrf @method('DELETE')<button class="text-sm text-rose-600 dark:text-rose-300">Delete</button></form></div>@if($snapshot->status === 'ready')<form method="POST" action="{{ route('snapshots.restore', $snapshot) }}" class="mt-3 flex max-w-lg gap-2">@csrf<input class="field mt-0" name="confirmation" placeholder="Type {{ $server->hostname }}"><button class="button-secondary text-amber-600 dark:text-amber-300">Restore server</button></form>@endif @if($snapshot->failure_reason)<p class="mt-2 text-xs text-rose-600 dark:text-rose-300">{{ $snapshot->failure_reason }}</p>@endif</div>@empty<p class="py-5 text-sm text-slate-500 dark:text-slate-400">No provider snapshots.</p>@endforelse</div></section>
    <section class="panel"><h2 class="font-semibold">Database recovery points</h2><div class="mt-5 divide-y divide-slate-100 dark:divide-white/5">@forelse($server->databases->flatMap->backups->where('type', 'export')->sortByDesc('created_at') as $backup)<div class="py-4"><div class="flex flex-wrap justify-between gap-3"><span>{{ $backup->database->name }} / {{ $backup->created_at->toDayDateTimeString() }}</span><span class="text-sm capitalize text-slate-500 dark:text-slate-400">{{ $backup->status }} @if($backup->size)/ {{ Number::fileSize($backup->size) }} @endif</span></div>@if($backup->status === 'ready')<div class="mt-3 flex flex-wrap gap-3"><a class="button-secondary" href="{{ route('database-backups.download', $backup) }}">Download</a><form method="POST" action="{{ route('database-backups.restore', $backup) }}" class="flex gap-2">@csrf<input class="field mt-0" name="confirmation" placeholder="Type {{ $backup->database->name }}"><button class="button-secondary text-amber-600 dark:text-amber-300">Restore database</button></form></div>@endif</div>@empty<p class="py-5 text-sm text-slate-500 dark:text-slate-400">No database recovery points.</p>@endforelse</div></section>
</div>
